name: GoReleaser in Action

on:
  push:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Tag the reposity
        run: git tag -f v0.0.1

      - name: Release with Goreleaser
        run: goreleaser release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Remove the repo from the runner
        run: |
          cd ..
          rm -rf DOB-gorelease
