name: GoReleaser in Action

on:
  push:
    branches:
      - main

# permissions:
#   contents: write

jobs:
  goreleaser:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Clone the repo
        run: git clone https://github.com/nsshaddox/DOB-gorelease.git

      # - name: Initialize Modules
      #   run: ls && go mod init main
      - name: Tag the reposity
        run: git tag v0.0.1

      - name: Initialize Goreleaser
        run: goreleaser init

      - name: Release with Goreleaser
        run: goreleaser release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      
