name: GoReleaser in Action

on:
  push:
    branches:
      - main

# permissions:
#   contents: write

jobs:
  goreleaser:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Clone the repo
        run: git clone https://github.com/nsshaddox/DOB-gorelease.git

      - name: Initialize Modules
        run: cd DOB-releaase && go mod init main

      # - name: Release with Goreleaser
      #   run: goreleaser release --snapshot --skip-publish --rm-dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      
